sSRC :=src/SecretSpies
LIB :=lib

INPUT_FILES := \
    $(LIB)/jquery/jquery-2.1.0.min.js \
	$(LIB)/phaser/phaser.js \
	\
	$(SRC)/SecretSpies.js \
	$(SRC)/GameState.js \
	$(SRC)/FinishedLevelState.js \
	$(SRC)/NewYorkDeathState.js \
	$(SRC)/NewYorkLevelState.js \
	$(SRC)/IqaluitDeathState.js \
	$(SRC)/IqaluitLevelState.js \
	$(SRC)/NorthAmericaState.js \
	$(SRC)/LondonDeathState.js \
	$(SRC)/LondonLevelState.js \
	$(SRC)/EuropeState.js \
	$(SRC)/BeijingLevelState.js \
	$(SRC)/AsiaState.js \
	$(SRC)/CairoDeathState.js \
	$(SRC)/CairoLevelState.js \
	$(SRC)/AfricaState.js \
	$(SRC)/WorldMapState.js \
	$(SRC)/StoryState.js \
	$(SRC)/MainMenuState.js \
	\
	$(SRC)/Bootstrap.js